preprocessing:
  resize:
    enabled: True
    height: 1000
    return_pil: False

  blurring:
    enabled: True
    type: 0  # 0: Gaussian, 1: Median, 2: Bilateral
    kernel_size: 5

  morphological_transformations:
    enabled: False
    kernel_size: 5
    iterations: 3

  thresholding:
    enabled: False
    adaptive: True

  erode_and_dilate:
    enabled: True
    kernel_size: 5
    dilate_iterations: 3
    erode_iterations: 2

  canny_edge_detection:
    enabled: True
    low_threshold: 50
    high_threshold: 150

transformation:
  template:
    path: "template/template_0.jpg"
